services:
  - type: web
    name: odds-analysis-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: UPDATE_INTERVAL
        value: 30
      - key: CONFIDENCE_THRESHOLD
        value: 75
      - key: VALUE_THRESHOLD
        value: 5
    autoDeploy: true
    healthCheckPath: /health
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - templates/**
        - static/**
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 